# Use nottirb's base builder image for Fuzzing Rust as the builder stage
FROM ghcr.io/nottirb/fuzz-rust:latest as builder

# Add source to the build stage
ADD . /yul
WORKDIR /yul

# Build the fuzz targets
RUN cd ./fuzz && cargo +nightly hfuzz build

# Use Ubuntu 20.04 as the final image
FROM ubuntu:20.04

# Copy the fuzz targets from the builder stage
COPY --from=builder yul/fuzz/hfuzz_target/x86_64-unknown-linux-gnu/release/fuzz_parse /